// Format a Finding as a HackerOne-style submission markdown report.
//
// Output template follows the de-facto bug-bounty report structure:
//   - Title
//   - Summary
//   - Steps to Reproduce
//   - Impact
//   - CWE / OWASP classification
//   - CVSS vector + score
//   - Supporting Materials (optional)
//   - Researcher Recommendation
//
// All sections are renderable from a Finding without external data.
// PII redaction is the caller's responsibility (apply src/safety.ts:redactPii
// to user-controlled fields BEFORE passing them in if they came from logs).

import type { Finding, Severity } from '../types.js';

export interface ReportFormatOptions {
  includeClassificationSection?: boolean;
  /** Override the researcher-attribution line in the footer. */
  researcher?: string;
}

export function formatFinding(finding: Finding, opts: ReportFormatOptions = {}): string {
  const lines: string[] = [];
  lines.push(`# ${finding.title}`);
  lines.push('');

  lines.push('## Summary');
  lines.push(finding.description || '_(no description)_');
  lines.push('');

  if (finding.reproduction) {
    lines.push('## Steps to Reproduce');
    lines.push(finding.reproduction);
    lines.push('');
  }

  lines.push('## Impact');
  lines.push(impactNarrative(finding.severity, finding.cvssScore));
  lines.push('');

  if (opts.includeClassificationSection !== false) {
    lines.push('## Classification');
    lines.push(`- **Asset:** \`${finding.asset}\``);
    if (finding.cwe) lines.push(`- **CWE:** ${finding.cwe}`);
    if (finding.owasp) lines.push(`- **OWASP Top-10 (2021):** ${finding.owasp}`);
    if (finding.severity) lines.push(`- **Severity:** ${finding.severity}`);
    if (finding.cvssScore !== undefined) lines.push(`- **CVSS Base Score:** ${finding.cvssScore}`);
    if (finding.cvssVector) lines.push(`- **CVSS Vector:** \`${finding.cvssVector}\``);
    lines.push('');
  }

  lines.push('## Researcher Recommendation');
  lines.push(recommendationFor(finding));
  lines.push('');

  lines.push('---');
  lines.push(`_Generated by @metaharness/hackerone v0.1.0${opts.researcher ? ` for ${opts.researcher}` : ''}_`);

  return lines.join('\n');
}

function impactNarrative(severity: Severity | undefined, score: number | undefined): string {
  const sev = severity ?? 'medium';
  const scoreStr = score !== undefined ? ` (CVSS base ${score})` : '';
  switch (sev) {
    case 'critical':
      return `**Critical${scoreStr}** — full compromise of confidentiality, integrity, or availability. Attacker can gain admin/root, exfiltrate sensitive data, or take the service offline at scale.`;
    case 'high':
      return `**High${scoreStr}** — significant compromise. Attacker can escalate privileges, access other users' data, or trigger material business impact.`;
    case 'medium':
      return `**Medium${scoreStr}** — partial compromise. Some data exposure, limited unauthorized access, or moderate availability impact.`;
    case 'low':
      return `**Low${scoreStr}** — minor compromise or hardening gap. Limited material impact in most scenarios.`;
    case 'none':
      return `**Informational${scoreStr}** — no direct exploitability; useful as defense-in-depth context.`;
    default:
      return `**Impact${scoreStr}** — see description.`;
  }
}

function recommendationFor(finding: Finding): string {
  const sev = finding.severity ?? 'medium';
  const urgency = sev === 'critical' || sev === 'high' ? 'immediately' : 'in the next sprint';
  const cweHint = finding.cwe ? ` ${finding.cwe}-class` : '';
  return (
    `Address this${cweHint} finding ${urgency}. Reproduce in a staging environment first, ` +
    `then apply the standard mitigation for the CWE (see CWE database). Validate the fix by ` +
    `re-running the repro steps and confirming the unsafe behavior no longer occurs.`
  );
}
