// Core types for @metaharness/hackerone.
//
// Mirrors HackerOne's report/program shape but deliberately narrowed to
// the fields the harness operates on. The full HackerOne API exposes many
// more fields; we add them as needed rather than overfitting to a wire
// format that may change.

/** CVSS-derived severity bands matching HackerOne's own classification. */
export type Severity = 'none' | 'low' | 'medium' | 'high' | 'critical';

/** A HackerOne program — the target an organization runs bug bounties on. */
export interface Program {
  handle: string;
  name: string;
  scope: ScopeItem[];
  outOfScope: ScopeItem[];
  /** Whether reports for this program have monetary bounties. */
  offersBounties: boolean;
  /** ISO 8601. */
  updatedAt?: string;
}

/** A single in-scope (or out-of-scope) asset. */
export interface ScopeItem {
  /** e.g., "*.example.com", "ios", "android", "api.example.com" */
  identifier: string;
  /** e.g., "URL", "DOMAIN", "IOS_APP_STORE", "ANDROID_PLAY_STORE", "API" */
  assetType: string;
  maxSeverity?: Severity;
  /** Free-text from the program. */
  instructions?: string;
  eligibleForBounty?: boolean;
}

/** A finding — submitted by a researcher OR generated by the harness. */
export interface Finding {
  id: string;
  title: string;
  /** Free-text technical description of the vulnerability. */
  description: string;
  /** CVSS v3.1 vector string, e.g. "AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H". */
  cvssVector?: string;
  cvssScore?: number;
  severity?: Severity;
  /** CWE id, e.g. "CWE-79". */
  cwe?: string;
  /** OWASP Top-10 (2021) category id, e.g. "A03:2021". */
  owasp?: string;
  /** Asset under test — should map to a Program.scope[] item. */
  asset: string;
  /** Repro steps as markdown. */
  reproduction?: string;
  /** ISO 8601 — when the finding was created. */
  createdAt?: string;
}

/** A HackerOne report — the unit of triage on the defender side. */
export interface Report {
  id: string;
  programHandle: string;
  finding: Finding;
  state: ReportState;
  /** Free-text reporter notes (the researcher's submission). */
  reporterNotes?: string;
  /** ISO 8601. */
  submittedAt?: string;
  /** Bounty awarded, if any (USD). */
  bountyAmount?: number;
}

export type ReportState =
  | 'new'
  | 'triaged'
  | 'needs-more-info'
  | 'duplicate'
  | 'not-applicable'
  | 'informative'
  | 'resolved'
  | 'spam';

/** A triage verdict — emitted by the defender pipeline. */
export interface TriageVerdict {
  reportId: string;
  /** Recommended new state. */
  recommendedState: ReportState;
  severity: Severity;
  cvssScore?: number;
  inScope: boolean;
  duplicateOf?: string;
  /** Confidence in the verdict, 0..1. */
  confidence: number;
  /** Human-readable reasoning trail. */
  reasoning: string[];
}

/** A scope-analysis result — emitted by the researcher pipeline. */
export interface ScopeAnalysis {
  programHandle: string;
  /** Assets the researcher should test, ranked by maxSeverity. */
  testableAssets: ScopeItem[];
  /** Suggested test families for each asset (e.g., XSS, SSRF). */
  suggestedChecks: Array<{ asset: string; checks: string[] }>;
  /** Out-of-scope assets to AVOID (defensive — surface them clearly). */
  forbidden: ScopeItem[];
  /** Whether the program offers bounties (cost-of-time signal). */
  offersBounties: boolean;
}

/** Result of API key resolution — tracks where the key came from. */
export interface KeyResolution {
  found: boolean;
  /** Where the key was sourced from (for diagnostics; never logs the value). */
  source: 'env' | 'dotenv' | 'gcp' | 'none';
  /** Length of the key (echo for diagnostics; never the key itself). */
  length: number;
  /** First 4 chars + length for tail-of-log identification. Never the full key. */
  prefix?: string;
}
